*** Variables ***
# variable data
${data_deskname_1}          (AT) DESK 01
${data_deskname_2}          (AT) DESK 02
${data_deskname_3}          (AT) DESK 03
${data_default_pharmacy}    (AT) Farmasi Racikan
${data_lines1}              (AT) Pendaftaran Pribadi
${data_lines2}              (AT) Farmasi Racikan
${data_lines3}              (AT) KASIR
${data_pasien_test}         (AT) Pasien
${data_dokter_test}         dr. Andreas Andy Atmadja, Sp.S, Mkes
${data_dokter_test2}        drg. Selvy Mulyawan
${data_tipe_test}           WALKIN
${data_treatment_test}      Radiologi 1
${data_treatment_test2}     Physiotherapy
${data_visit_badge}         URGENT
${data_pasien_badge}        VIP
${data_notes}               Test data notes

@{personal_info}
...                         RANGGA HENDARMIN
...                         07071999
...                         3200000000000
...                         0000123
...                         085871740847
...                         ranggahendarmin07@gmail.com

# variable data login test
${admin_username_valid}     admin_caller
${staff_username_valid}     unit_caller
${password_valid}           Mandaya123
